### ISSUE TITLE
meta-conduct error: `Exception 'TreeVersionList' object has no attribute 'write_out' in processor`

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad-metalad#140]
_System: Mac 
DataLad: 0.15.0
Metalad: 0.2.1+334.gb4799a5_

---

I'm running `meta-conduct` with a package-provided pipeline on a DataLad dataset (specifically, a subdataset of the StudyForrest dataset) and getting the reported error.

Command:
```
datalad meta-conduct datalad_metalad/pipelines/extract_metadata_pipeline.json \
traverser:/Users/jsheunis/Documents/psyinf/Data/sfdata_21sep/studyforrest-data/original/3T_multiresolution_fmri \
extractor:Dataset \
extractor:metalad_core_dataset adder:True
```

Full error trace:
```
[ERROR  ] Exception 'TreeVersionList' object has no attribute 'write_out' in processor <Future at 0x7fe28bde7430 state=finished raised AttributeError>
  [58 similar messages have been suppressed; disable with datalad.ui.suppress-similar-results=off]
meta_conduct(error): [concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/jsheunis/opt/miniconda3/envs/metalad/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/jsheunis/opt/miniconda3/envs/metalad/lib/python3.9/site-packages/datalad_metalad/processor/base.py", line 23, in execute
    return context, self.process(pipeline_element)
  File "/Users/jsheunis/opt/miniconda3/envs/metalad/lib/python3.9/site-packages/datalad_metalad/processor/add.py", line 76, in process
    for add_result in meta_add(metadata=metadata_record,
  File "/Users/jsheunis/opt/miniconda3/envs/metalad/lib/python3.9/site-packages/datalad/interface/utils.py", line 483, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/Users/jsheunis/opt/miniconda3/envs/metalad/lib/python3.9/site-packages/datalad/interface/utils.py", line 476, in return_func
    results = list(results)
  File "/Users/jsheunis/opt/miniconda3/envs/metalad/lib/python3.9/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/Users/jsheunis/opt/miniconda3/envs/metalad/lib/python3.9/site-packages/datalad/interface/utils.py", line 574, in _process_results
    for res in results:
  File "/Users/jsheunis/opt/miniconda3/envs/metalad/lib/python3.9/site-packages/datalad_metalad/add.py", line 321, in __call__
    yield from add_dataset_metadata(dataset.pathobj, add_parameter)
  File "/Users/jsheunis/opt/miniconda3/envs/metalad/lib/python3.9/site-packages/datalad_metalad/add.py", line 531, in add_dataset_metadata
    tree_version_list.write_out(realm)
AttributeError: 'TreeVersionList' object has no attribute 'write_out'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jsheunis/opt/miniconda3/envs/metalad/lib/python3.9/site-packages/datalad_metalad/conduct.py", line 237, in process_parallel
    source_index, pipeline_element = future.result()
  File "/Users/jsheunis/opt/miniconda3/envs/metalad/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/Users/jsheunis/opt/miniconda3/envs/metalad/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
AttributeError: 'TreeVersionList' object has no attribute 'write_out'
]
```

If I run the same command with `adder:True` removed and using an adjusted pipeline configuration where the `add` processor is removed, there is no error.

**Comment by christian-monch** [comment]
Thx for the report.

With datalad-metalad master b4799a53822554185db73b61adcaf52545102c47 I don't see the error here.

It seems like a mismatch between datalad-metalad version and the metadata-model version. The metadata-model version should be `beta1` (the method `write_out` did not exist in earlier versions of metadata-model). It should have been installed in your environment if you execute `pip install -r requirements-devel.txt` in the datalad-metalad source directory

**Comment by jsheunis** [comment]
I created a new conda environment and reinstalled datalad and datalad-metalad, and now it seems to work without error.

I distinctly remember previously installing the updated version of datalad-metalad in the previous existing environment (both using `pip install -r requirements-devel.txt` and `pip install -f -e .`) and that didn't solve the issue previously. Could it be that the updated version of the metadata-model is not overwritten with the updated installation in the existing environment?

PS: the above is applicable for #141 as well
