### ISSUE TITLE
None MRR not caught

### ISSUE THREAD

**Issue by christian-monch** [datalad/datalad-metalad#193]
None-metadata root record is handed down to methods in dump

```
(datalad-metalad-20211102) cristian@alligator:~/datalad/longnow-podcasts> datalad meta-dump "*"
[ERROR  ] AttributeError('NoneType' object has no attribute 'ensure_mapped') (AttributeError) 
(datalad-metalad-20211102) cristian@alligator:~/datalad/longnow-podcasts> datalad --dbg meta-dump "*"
Traceback (most recent call last):
  File "/home/cristian/venv/datalad-metalad-20211102/bin/datalad", line 8, in <module>
    sys.exit(main())
  File "/home/cristian/venv/datalad-metalad-20211102/lib/python3.6/site-packages/datalad/cmdline/main.py", line 211, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/cristian/venv/datalad-metalad-20211102/lib/python3.6/site-packages/datalad/interface/base.py", line 786, in call_from_parser
    ret = list(ret)
  File "/home/cristian/venv/datalad-metalad-20211102/lib/python3.6/site-packages/datalad/interface/utils.py", line 408, in generator_func
    allkwargs):
  File "/home/cristian/venv/datalad-metalad-20211102/lib/python3.6/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/home/cristian/Develop/datalad-metalad/datalad_metalad/dump.py", line 519, in __call__
    recursive)
  File "/home/cristian/Develop/datalad-metalad/datalad_metalad/dump.py", line 329, in dump_from_dataset_tree
    mrr)
  File "/home/cristian/Develop/datalad-metalad/datalad_metalad/dump.py", line 130, in show_dataset_metadata
    purge_metadata_root_record = metadata_root_record.ensure_mapped()
AttributeError: 'NoneType' object has no attribute 'ensure_mapped'

> /home/cristian/Develop/datalad-metalad/datalad_metalad/dump.py(130)show_dataset_metadata()
-> purge_metadata_root_record = metadata_root_record.ensure_mapped()
```

**Comment by christian-monch** [comment]
fixed in efaa915ac884d365e5ff61c5d5c334de8c4479a5
