### ISSUE TITLE
test_empty_dataset_error is flaky on datalad tests

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-metalad#222]
I thought it was somehow effect of my changes in https://github.com/datalad/datalad/pull/6567 

<details>
<summary>but it happened before and in other PRs</summary> 

```shell
(git)smaug:/mnt/datasets/datalad/ci/logs/2022/03[master]git
$> git grep 'No installed dataset found'
07/pr/6521/07fe680/github-Extensions-4700-failed/3_test (datalad-metalad).txt:2022-03-07T10:49:12.5908686Z   'message': 'No installed dataset found at '
07/pr/6521/07fe680/github-Extensions-4700-failed/3_test (datalad-metalad).txt:2022-03-07T10:49:12.5918990Z   'message': 'No installed dataset found at '
07/pr/6521/07fe680/github-Extensions-4700-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-07T10:49:12.5908680Z   'message': 'No installed dataset found at '
07/pr/6521/07fe680/github-Extensions-4700-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-07T10:49:12.5918988Z   'message': 'No installed dataset found at '
07/pr/6521/feb4ac3/github-Extensions-4701-failed/3_test (datalad-metalad).txt:2022-03-07T10:49:50.2263986Z   'message': 'No installed dataset found at '
07/pr/6521/feb4ac3/github-Extensions-4701-failed/3_test (datalad-metalad).txt:2022-03-07T10:49:50.2274326Z   'message': 'No installed dataset found at '
07/pr/6521/feb4ac3/github-Extensions-4701-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-07T10:49:50.2263983Z   'message': 'No installed dataset found at '
07/pr/6521/feb4ac3/github-Extensions-4701-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-07T10:49:50.2274323Z   'message': 'No installed dataset found at '
09/pr/6529/32531d0/github-Extensions-4710-failed/3_test (datalad-metalad).txt:2022-03-09T20:08:02.0943233Z   'message': 'No installed dataset found at '
09/pr/6529/32531d0/github-Extensions-4710-failed/3_test (datalad-metalad).txt:2022-03-09T20:08:02.0953293Z   'message': 'No installed dataset found at '
09/pr/6529/32531d0/github-Extensions-4710-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-09T20:08:02.0943229Z   'message': 'No installed dataset found at '
09/pr/6529/32531d0/github-Extensions-4710-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-09T20:08:02.0953290Z   'message': 'No installed dataset found at '
09/push/master/7d2c782/github-Extensions-4713-failed/3_test (datalad-metalad).txt:2022-03-09T20:11:24.2672897Z   'message': 'No installed dataset found at '
09/push/master/7d2c782/github-Extensions-4713-failed/3_test (datalad-metalad).txt:2022-03-09T20:11:24.2684195Z   'message': 'No installed dataset found at '
09/push/master/7d2c782/github-Extensions-4713-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-09T20:11:24.2672894Z   'message': 'No installed dataset found at '
09/push/master/7d2c782/github-Extensions-4713-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-09T20:11:24.2684192Z   'message': 'No installed dataset found at '
09/push/master/9a92da5/github-Extensions-4709-failed/3_test (datalad-metalad).txt:2022-03-09T13:33:40.3146792Z   'message': 'No installed dataset found at '
09/push/master/9a92da5/github-Extensions-4709-failed/3_test (datalad-metalad).txt:2022-03-09T13:33:40.3159010Z   'message': 'No installed dataset found at '
09/push/master/9a92da5/github-Extensions-4709-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-09T13:33:40.3146789Z   'message': 'No installed dataset found at '
09/push/master/9a92da5/github-Extensions-4709-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-09T13:33:40.3159006Z   'message': 'No installed dataset found at '
10/pr/6532/bd4b4b7/github-Extensions-4714-failed/3_test (datalad-metalad).txt:2022-03-10T08:22:43.5045730Z   'message': 'No installed dataset found at '
10/pr/6532/bd4b4b7/github-Extensions-4714-failed/3_test (datalad-metalad).txt:2022-03-10T08:22:43.5059656Z   'message': 'No installed dataset found at '
10/pr/6532/bd4b4b7/github-Extensions-4714-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-10T08:22:43.5045726Z   'message': 'No installed dataset found at '
10/pr/6532/bd4b4b7/github-Extensions-4714-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-10T08:22:43.5059652Z   'message': 'No installed dataset found at '
10/pr/6533/e7f800a/github-Extensions-4715-failed/3_test (datalad-metalad).txt:2022-03-10T09:11:28.4080519Z   'message': 'No installed dataset found at '
10/pr/6533/e7f800a/github-Extensions-4715-failed/3_test (datalad-metalad).txt:2022-03-10T09:11:28.4091443Z   'message': 'No installed dataset found at '
10/pr/6533/e7f800a/github-Extensions-4715-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-10T09:11:28.4080515Z   'message': 'No installed dataset found at '
10/pr/6533/e7f800a/github-Extensions-4715-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-10T09:11:28.4091440Z   'message': 'No installed dataset found at '
16/pr/6557/a2967e4/github-Extensions-4764-failed/3_test (datalad-metalad).txt:2022-03-16T17:19:19.4887116Z ValueError: No installed dataset found at /tmp/datalad_temp_test_empty_dataset_error8ncv5z8b.
16/pr/6557/a2967e4/github-Extensions-4764-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-16T17:19:19.4887112Z ValueError: No installed dataset found at /tmp/datalad_temp_test_empty_dataset_error8ncv5z8b.
17/push/maint/0f6cd1b/github-Extensions-4765-failed/3_test (datalad-metalad).txt:2022-03-17T06:15:18.4994297Z ValueError: No installed dataset found at /tmp/datalad_temp_test_empty_dataset_error6vguy6yl.
17/push/maint/0f6cd1b/github-Extensions-4765-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-17T06:15:18.4994293Z ValueError: No installed dataset found at /tmp/datalad_temp_test_empty_dataset_error6vguy6yl.
18/pr/6553/0ead59f/travis-13702-failed/4.txt:datalad.support.exceptions.NoDatasetFound: No installed dataset found at /tmp/datalad_temp_test_install_subds_with_spacetfd1j2jl
18/pr/6553/71c67c9/travis-13701-failed/4.txt:datalad.support.exceptions.NoDatasetFound: No installed dataset found at /tmp/datalad_temp_test_install_subds_with_space42ykmnoq
18/pr/6567/c7a4f29/github-Extensions-4779-failed/3_test (datalad-metalad).txt:2022-03-18T02:47:41.1880158Z ValueError: No installed dataset found at /tmp/datalad_temp_test_empty_dataset_errorfvi09v94.
18/pr/6567/c7a4f29/github-Extensions-4779-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-18T02:47:41.1880155Z ValueError: No installed dataset found at /tmp/datalad_temp_test_empty_dataset_errorfvi09v94.
18/pr/6567/ede2a2a/github-Extensions-4794-failed/3_test (datalad-metalad).txt:2022-03-18T20:11:16.2332625Z ValueError: No installed dataset found at /tmp/datalad_temp_test_empty_dataset_errorukltg20b.
18/pr/6567/ede2a2a/github-Extensions-4794-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-18T20:11:16.2332622Z ValueError: No installed dataset found at /tmp/datalad_temp_test_empty_dataset_errorukltg20b.
git grep 'No installed dataset found'  1.54s user 4.62s system 608% cpu 1.013 total
(dev3) 2 3841.....................................:Fri 18 Mar 2022 09:31:45 PM EDT:.
(git)smaug:/mnt/datasets/datalad/ci/logs/2022/03[master]git
$> git grep 'ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error'
07/pr/6521/07fe680/github-Extensions-4700-failed/3_test (datalad-metalad).txt:2022-03-07T10:49:12.5890344Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
07/pr/6521/07fe680/github-Extensions-4700-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-07T10:49:12.5890340Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
07/pr/6521/feb4ac3/github-Extensions-4701-failed/3_test (datalad-metalad).txt:2022-03-07T10:49:50.2215444Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
07/pr/6521/feb4ac3/github-Extensions-4701-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-07T10:49:50.2215437Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
09/pr/6529/32531d0/github-Extensions-4710-failed/3_test (datalad-metalad).txt:2022-03-09T20:08:02.0875112Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
09/pr/6529/32531d0/github-Extensions-4710-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-09T20:08:02.0875109Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
09/push/master/7d2c782/github-Extensions-4713-failed/3_test (datalad-metalad).txt:2022-03-09T20:11:24.2588903Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
09/push/master/7d2c782/github-Extensions-4713-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-09T20:11:24.2588899Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
09/push/master/9a92da5/github-Extensions-4709-failed/3_test (datalad-metalad).txt:2022-03-09T13:33:40.3123324Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
09/push/master/9a92da5/github-Extensions-4709-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-09T13:33:40.3123320Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
10/pr/6532/bd4b4b7/github-Extensions-4714-failed/3_test (datalad-metalad).txt:2022-03-10T08:22:43.4975506Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
10/pr/6532/bd4b4b7/github-Extensions-4714-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-10T08:22:43.4975501Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
10/pr/6533/e7f800a/github-Extensions-4715-failed/3_test (datalad-metalad).txt:2022-03-10T09:11:28.4011066Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
10/pr/6533/e7f800a/github-Extensions-4715-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-10T09:11:28.4011063Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
16/pr/6557/a2967e4/github-Extensions-4764-failed/3_test (datalad-metalad).txt:2022-03-16T17:19:19.4747720Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
16/pr/6557/a2967e4/github-Extensions-4764-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-16T17:19:19.4747715Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
17/push/maint/0f6cd1b/github-Extensions-4765-failed/3_test (datalad-metalad).txt:2022-03-17T06:15:18.4957717Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
17/push/maint/0f6cd1b/github-Extensions-4765-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-17T06:15:18.4957687Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
18/pr/6567/c7a4f29/github-Extensions-4779-failed/3_test (datalad-metalad).txt:2022-03-18T02:47:41.1768428Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
18/pr/6567/c7a4f29/github-Extensions-4779-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-18T02:47:41.1768425Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
18/pr/6567/ede2a2a/github-Extensions-4794-failed/3_test (datalad-metalad).txt:2022-03-18T20:11:16.2182223Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
18/pr/6567/ede2a2a/github-Extensions-4794-failed/test (datalad-metalad)/12_datalad-metalad tests.txt:2022-03-18T20:11:16.2182219Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
git grep 'ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error'  4.83s user 4.24s system 695% cpu 1.305 total

```
</details>

```
2022-03-10T09:11:28.4010749Z ======================================================================
2022-03-10T09:11:28.4011063Z ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
2022-03-10T09:11:28.4011965Z ----------------------------------------------------------------------
2022-03-10T09:11:28.4012411Z Traceback (most recent call last):
2022-03-10T09:11:28.4069819Z   File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
2022-03-10T09:11:28.4070226Z     self.test(*self.arg)
2022-03-10T09:11:28.4071057Z   File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 874, in _wrap_with_tempfile
2022-03-10T09:11:28.4072287Z     return t(*(arg + (filename,)), **kw)
2022-03-10T09:11:28.4072950Z   File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad_metalad/tests/test_extract.py", line 50, in test_empty_dataset_error
2022-03-10T09:11:28.4073549Z     meta_extract, extractorname="metalad_core")
2022-03-10T09:11:28.4073957Z   File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/unittest/case.py", line 756, in assertRaises
2022-03-10T09:11:28.4074415Z     return context.handle('assertRaises', args, kwargs)
2022-03-10T09:11:28.4074810Z   File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/unittest/case.py", line 178, in handle
2022-03-10T09:11:28.4075124Z     callable_obj(*args, **kwargs)
2022-03-10T09:11:28.4075819Z   File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 447, in eval_func
2022-03-10T09:11:28.4076331Z     return return_func(*args, **kwargs)
2022-03-10T09:11:28.4076866Z   File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 439, in return_func
2022-03-10T09:11:28.4077543Z     results = list(results)
2022-03-10T09:11:28.4078388Z   File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 426, in generator_func
2022-03-10T09:11:28.4078975Z     msg="Command did not complete successfully")
2022-03-10T09:11:28.4079376Z datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
2022-03-10T09:11:28.4079941Z [{'action': 'meta_extract',
2022-03-10T09:11:28.4080515Z   'message': 'No installed dataset found at '
2022-03-10T09:11:28.4081067Z              '/tmp/datalad_temp_test_empty_dataset_error4pososbp',
2022-03-10T09:11:28.4081346Z   'path': '.',
2022-03-10T09:11:28.4081589Z   'status': 'error',
2022-03-10T09:11:28.4081826Z   'type': 'dataset'}]
```

it generally seems to pass more often than fail.  Underlying issue might actually be in datalad core, but since seems to happen only against datalad-metalad -- complaining here, but feel welcome to transfer if it is indeed core issue

**Comment by christian-monch** [comment]
I merge a PR, but I think the problem might be in the "repo"-property of `datalad.distribution.dataset.Dataset`

**Comment by christian-monch** [comment]
Closing this issue, due to no further response.
