### ISSUE TITLE
erroneous "is not in the subpath of " error when non normalized path is provided

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-metalad#256]
```shell
$> datalad -f json meta-conduct /mnt/datasets/datalad/crawl-catalog/3rd/fairly-big-catalog-workflow/conduct_pipelines/extract_file_metadata.json traverser.top_level_dir=../crawl/repronim/containers/ traverser.item_type=file extractor.extractor_type=file extractor.extractor_name=metalad_core 
[ERROR  ] '/mnt/datasets/datalad/crawl/repronim/containers' is not in the subpath of '/mnt/datasets/datalad/crawl-catalog/../crawl/repronim/containers' OR one path is relative and the other is absolute. (ValueError) 

$> datalad meta-conduct --version
datalad_metalad 0.3.3
```

and the error is erroneous since paths are "identical":
```
$> python3 -c 'import os.path; print(os.path.normpath("/mnt/datasets/datalad/crawl-catalog/../crawl/repronim/containers") == "/mnt/datasets/datalad/crawl/repronim/containers")'
True
```

traceback:

```shell
(git)smaug:/mnt/datasets/datalad/crawl-catalog[master]git
$> datalad --dbg -f json meta-conduct /mnt/datasets/datalad/crawl-catalog/3rd/fairly-big-catalog-workflow/conduct_pipelines/extract_file_metadata.json traverser.top_level_dir=../crawl/repronim/containers/ traverser.item_type=file extractor.extractor_type=file extractor.extractor_name=metalad_core
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-metalad/venvs/dev3/bin/datalad", line 8, in <module>
    sys.exit(main())
  File "/home/yoh/proj/datalad/datalad-metalad/venvs/dev3/lib/python3.9/site-packages/datalad/cli/main.py", line 140, in main
    _run(cmdlineargs)
  File "/home/yoh/proj/datalad/datalad-metalad/venvs/dev3/lib/python3.9/site-packages/datalad/cli/main.py", line 164, in _run
    ret = _run_with_debugger(namespace) \
  File "/home/yoh/proj/datalad/datalad-metalad/venvs/dev3/lib/python3.9/site-packages/datalad/cli/main.py", line 177, in _run_with_debugger
    return cmdlineargs.func(cmdlineargs)
  File "/home/yoh/proj/datalad/datalad-metalad/venvs/dev3/lib/python3.9/site-packages/datalad/cli/exec.py", line 107, in call_from_parser
    ret = list(ret)
  File "/home/yoh/proj/datalad/datalad-metalad/venvs/dev3/lib/python3.9/site-packages/datalad/interface/utils.py", line 357, in generator_func
    for r in _process_results(
  File "/home/yoh/proj/datalad/datalad-metalad/venvs/dev3/lib/python3.9/site-packages/datalad/interface/utils.py", line 544, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad-metalad/datalad_metalad/conduct.py", line 282, in __call__
    yield from process_parallel(
  File "/home/yoh/proj/datalad/datalad-metalad/datalad_metalad/conduct.py", line 300, in process_parallel
    for pipeline_data in provider_instance.next_object():
  File "/home/yoh/proj/datalad/datalad-metalad/datalad_metalad/pipeline/provider/datasettraverse.py", line 221, in next_object
    yield from self._traverse_dataset(self.fs_base_path)
  File "/home/yoh/proj/datalad/datalad-metalad/datalad_metalad/pipeline/provider/datasettraverse.py", line 202, in _traverse_dataset
    **self._get_dataset_result_part(dataset)
  File "/home/yoh/proj/datalad/datalad-metalad/datalad_metalad/pipeline/provider/datasettraverse.py", line 143, in _get_dataset_result_part
    "dataset_path": dataset.pathobj.relative_to(self.fs_base_path),
  File "/usr/lib/python3.9/pathlib.py", line 928, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '/mnt/datasets/datalad/crawl/repronim/containers' is not in the subpath of '/mnt/datasets/datalad/crawl-catalog/../crawl/repronim/containers' OR one path is relative and the other is absolute.

> /usr/lib/python3.9/pathlib.py(928)relative_to()
-> raise ValueError("{!r} is not in the subpath of {!r}"
```

**Comment by christian-monch** [comment]
Should be fixed in release 0.3.4
