### ISSUE TITLE
Current windows failures

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-metalad#37]
Currently investigating the Windows failures -- recording them here:

## Appveyor failures on master:

<details><summary>FAIL: datalad_metalad.extractors.tests.test_runprov.test_custom_dsmeta</summary>

```sh
======================================================================
FAIL: datalad_metalad.extractors.tests.test_runprov.test_custom_dsmeta
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 559, in newfunc
    return t(*(arg + (d,)), **kw)
  File "c:\projects\datalad-metalad\datalad_metalad\extractors\tests\test_runprov.py", line 51, in test_custom_dsmeta
    assert_result_count(res, 2)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 1335, in assert_result_count
    dumps(results, indent=1, default=lambda x: str(x))))
AssertionError: Got 1 instead of 2 expected results matching {}. Inspected 1 record(s):
[
 {
  "path": "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_tree_751ocp6e",
  "action": "meta_extract",
  "refds": "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_tree_751ocp6e",
  "metadata": {
   "metalad_runprov": {
    "@graph": [
     {
      "@id": "9868fe2af8918d6cdb7ff42952039ce1422209ce",
      "atTime": "2020-02-13T06:52:51+00:00",
      "rdfs:comment": "[DATALAD RUNCMD] pristine",
      "prov:wasAssociatedWith": {
       "@id": "3f70461cb7bf5c45308533ef6f730f8b"
      },
      "@type": "activity"
     },
     {
      "@id": "3f70461cb7bf5c45308533ef6f730f8b",
      "name": "DataLad Tester",
      "email": "test@example.com",
      "@type": "agent"
     }
    ],
    "@context": "http://openprovenance.org/prov.jsonld"
   }
  },
  "refcommit": "73db20dcb1c0a84a80fa5d7f5ee97adb40abaa40",
  "status": "ok",
  "type": "dataset"
 }
]

```
</details>

<details><summary>FAIL: datalad_metalad.tests.test_aggregate.test_aggregate_removal</summary>

```
======================================================================
FAIL: datalad_metalad.tests.test_aggregate.test_aggregate_removal
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 559, in newfunc
    return t(*(arg + (d,)), **kw)
  File "c:\projects\datalad-metalad\datalad_metalad\tests\test_aggregate.py", line 449, in test_aggregate_removal
    eq_(_get_contained_objs(base), _get_referenced_objs(base))
AssertionError: {'.datalad\\metadata\\objects\\2c\\796447dab124639242c7cb84d73c9886a7cc82.xz', '.datalad\\metadata\\objects\\22\\334930b0b35e58678ffff3e5332e9d3dacc5e3.xz', '.datalad\\metadata\\objects\\5c\\ef1118477b6bd588b32bcce2f6c649efbfc3c6.xz', '.datalad\\metadata\\objects\\f7\\e353c67d7c03cf80206ed77c0501340fb1166e.xz', '.datalad\\metadata\\objects\\b9\\ece1471887a834d8aeb0f0a6ac6d4497f8bda4.xz', '.datalad\\metadata\\objects\\22\\5e2be622c0a6e7e9cf2a2e29046ccba48888d0.xz'} != {'.datalad/metadata/objects/f7/e353c67d7c03cf80206ed77c0501340fb1166e.xz', '.datalad/metadata/objects/b9/ece1471887a834d8aeb0f0a6ac6d4497f8bda4.xz', '.datalad/metadata/objects/22/5e2be622c0a6e7e9cf2a2e29046ccba48888d0.xz', '.datalad/metadata/objects/2c/796447dab124639242c7cb84d73c9886a7cc82.xz', '.datalad/metadata/objects/22/334930b0b35e58678ffff3e5332e9d3dacc5e3.xz', '.datalad/metadata/objects/5c/ef1118477b6bd588b32bcce2f6c649efbfc3c6.xz'}
```
</details>

<details><summary>FAIL: datalad_metalad.tests.test_aggregate.test_reaggregate_with_unavailable_objects</summary>

```
======================================================================
FAIL: datalad_metalad.tests.test_aggregate.test_reaggregate_with_unavailable_objects
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 559, in newfunc
    return t(*(arg + (d,)), **kw)
  File "c:\projects\datalad-metalad\datalad_metalad\tests\test_aggregate.py", line 342, in test_reaggregate_with_unavailable_objects
    eq_(all(base.repo.file_has_content(objs)), True)
AssertionError: False != True
```
</details>

<details><summary>FAIL: datalad_metalad.tests.test_aggregate.test_reaggregate </summary>

```
======================================================================
FAIL: datalad_metalad.tests.test_aggregate.test_reaggregate
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 732, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\projects\datalad-metalad\datalad_metalad\tests\test_aggregate.py", line 681, in test_reaggregate
    eq_(good_state, ds.repo.get_hexsha())
AssertionError: '71437976ee6d1dd57153af9740b1931dabfa1cdf' != '5bf4e3845f71f78fcedb6e05305423906ce3ce4b'
```
</details>

<details><summary>FAIL: datalad_metalad.tests.test_base.test_get_refcommit</summary>

```
======================================================================
FAIL: datalad_metalad.tests.test_base.test_get_refcommit
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 732, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\projects\datalad-metalad\datalad_metalad\tests\test_base.py", line 79, in test_get_refcommit
    eq_(get_refcommit(ds), real_change)
AssertionError: '9eb37f392fb62e1d0dfbfb79343c0ed400a7e440' != '7b30fb98babb13a223f7ac21807dfdc459157212'
```
</details>

<details><summary>FAIL: datalad_metalad.tests.test_report.test_query</summary>

```
======================================================================
FAIL: datalad_metalad.tests.test_report.test_query
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 732, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 732, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\projects\datalad-metalad\datalad_metalad\tests\test_report.py", line 157, in test_query
    {k: v for k, v in iteritems(query_res[0]) if k not in strip},
AssertionError: {'type': 'dataset', 'status': 'ok', 'metadata': {'@graph': [{'@id': '3f70461cb7bf5c45308533ef6f730f8b', 'name': 'DataLad Tester', 'email': 'test@example.com', '@type': 'agent'}, {'version': '0-7-g4d4e3c4', 'hasPart': [{'@id': 'datalad:MD5E-s7--9a0364b9e99bb480dd25e1f0284c8555.dat', 'name': 'file.dat', '@type': 'DigitalDocument'}, {'@id': 'datalad:b9ca047bf60ea7328f637cd2bbac138ffa4a5df0', 'name': 'sub', 'identifier': 'datalad:6a322348-4e2e-11ea-8049-00155dfb566a', '@type': 'Dataset'}], 'dateModified': '2020-02-13T06:59:52+00:00', '@id': '4d4e3c4b18a4a20afee49e0eb1d878dcb439e413', 'hasContributor': {'@id': '3f70461cb7bf5c45308533ef6f730f8b'}, 'contentbytesize': 7, 'identifier': '67e35838-4e2e-11ea-820d-00155dfb566a', 'dateCreated': '2020-02-13T06:59:39+00:00', '@type': 'Dataset'}, {'contentbytesize': 7, '@id': 'datalad:MD5E-s7--9a0364b9e99bb480dd25e1f0284c8555.dat', 'name': 'file.dat'}], '@context': {'datalad': 'http://dx.datalad.org/', '@vocab': 'http://schema.org/'}}, 'refcommit': '4d4e3c4b18a4a20afee49e0eb1d878dcb439e413'} != {'type': 'dataset', 'status': 'ok', 'metadata': {'@graph': [{'@id': '3f70461cb7bf5c45308533ef6f730f8b', 'name': 'DataLad Tester', 'email': 'test@example.com', '@type': 'agent'}, {'version': '0-6-g8cf1904', 'hasPart': [{'@id': 'datalad:MD5E-s7--9a0364b9e99bb480dd25e1f0284c8555.dat', 'name': 'file.dat', '@type': 'DigitalDocument'}, {'@id': 'datalad:b9ca047bf60ea7328f637cd2bbac138ffa4a5df0', 'name': 'sub', 'identifier': 'datalad:6a322348-4e2e-11ea-8049-00155dfb566a', '@type': 'Dataset'}], 'dateModified': '2020-02-13T06:59:48+00:00', '@id': '8cf1904e8ca46f472e27bc7351c702f88b8ed49e', 'hasContributor': {'@id': '3f70461cb7bf5c45308533ef6f730f8b'}, 'contentbytesize': 7, 'identifier': '67e35838-4e2e-11ea-820d-00155dfb566a', 'dateCreated': '2020-02-13T06:59:39+00:00', '@type': 'Dataset'}, {'contentbytesize': 7, '@id': 'datalad:MD5E-s7--9a0364b9e99bb480dd25e1f0284c8555.dat', 'name': 'file.dat'}], '@context': {'datalad': 'http://dx.datalad.org/', '@vocab': 'http://schema.org/'}}, 'refcommit': '8cf1904e8ca46f472e27bc7351c702f88b8ed49e'}
```
</details>

These failures are identical on our Windows test box.

## Appveyor failures on #34

<details>
<summary>FAIL: datalad_metalad.tests.test_aggregate.test_aggregate_into_top_no_extraction</summary>

```
======================================================================
FAIL: datalad_metalad.tests.test_aggregate.test_aggregate_into_top_no_extraction
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 732, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\projects\datalad-metalad\datalad_metalad\tests\test_aggregate.py", line 889, in test_aggregate_into_top_no_extraction
    type='dataset'
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 1335, in assert_result_count
    dumps(results, indent=1, default=lambda x: str(x))))
AssertionError: Got 0 instead of 1 expected results matching {'action': 'meta_extract', 'status': 'notneeded', 'type': 'dataset'}. Inspected 4 record(s):
[
 {
  "action": "add",
  "type": "file",
  "path": "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_lqek3pbt\\.datalad\\metadata\\aggregate_v1.json",
  "refds": "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_lqek3pbt",
  "status": "ok",
  "message": "",
  "key": null
 },
 {
  "action": "add",
  "type": "file",
  "path": "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_lqek3pbt\\.datalad\\metadata\\objects\\3e\\9759429956d9136b87cf62f4e1191104026af3.xz",
  "refds": "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_lqek3pbt",
  "status": "ok",
  "message": "",
  "key": "MD5E-s460--e1f9a1a624123fc591723b73a3f5944d.xz"
 },
 {
  "type": "dataset",
  "status": "ok",
  "path": "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_lqek3pbt",
  "refds": "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_lqek3pbt",
  "action": "save"
 },
 {
  "type": "dataset",
  "status": "ok",
  "path": "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_lqek3pbt",
  "action": "meta_aggregate"
 }
]

```
</details>

**Comment by mih** [comment]
At first glance this all relate to the switch from direct mode to adjusted branches on windows. In #39 I have added a CI run on a crippled file system that will shed light on what is windows-specific.

DataLad core is generally working on adjusted branch repositories, but support for subdatasets in adjusted branches is only coming via https://github.com/datalad/datalad/pull/4275 -- this is critical for updating some of the test in here.

**Comment by mih** [comment]
I think we can close this. It will be around as a data point even in a closed state. There is nothing immediately actionable here after such a long time.
