### ISSUE TITLE
Import `BaseMetadataExtractor` from `datalad-deprecated`

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad-metalad#376]
I'm running extraction using the `dicom.py` extractor from `datalad-neuroimaging`:

```
pip install datalad
pip install datalad-metalad
pip install datalad-neuroimaging

datalad -f json meta-extract -d . dicom <relative_path_to_a_dicom_file>

Traceback (most recent call last):
  File "/Users/jsheunis/opt/miniconda3/envs/icf/bin/datalad", line 8, in <module>
    sys.exit(main())
  File "/Users/jsheunis/opt/miniconda3/envs/icf/lib/python3.10/site-packages/datalad/cli/main.py", line 143, in main
    _run(cmdlineargs)
  File "/Users/jsheunis/opt/miniconda3/envs/icf/lib/python3.10/site-packages/datalad/cli/main.py", line 167, in _run
    ret = _run_with_debugger(namespace) \
  File "/Users/jsheunis/opt/miniconda3/envs/icf/lib/python3.10/site-packages/datalad/cli/main.py", line 181, in _run_with_debugger
    return cmdlineargs.func(cmdlineargs)
  File "/Users/jsheunis/opt/miniconda3/envs/icf/lib/python3.10/site-packages/datalad/cli/exec.py", line 107, in call_from_parser
    ret = list(ret)
  File "/Users/jsheunis/opt/miniconda3/envs/icf/lib/python3.10/site-packages/datalad/interface/base.py", line 873, in _execute_command_
    for r in _process_results(
  File "/Users/jsheunis/opt/miniconda3/envs/icf/lib/python3.10/site-packages/datalad/interface/utils.py", line 319, in _process_results
    for res in results:
  File "/Users/jsheunis/opt/miniconda3/envs/icf/lib/python3.10/site-packages/datalad_metalad/extract.py", line 322, in __call__
    yield from do_extraction(ep=extraction_arguments)
  File "/Users/jsheunis/opt/miniconda3/envs/icf/lib/python3.10/site-packages/datalad_metalad/extract.py", line 374, in do_extraction
    yield from legacy_extractor_map[extractor_type](ep)
  File "/Users/jsheunis/opt/miniconda3/envs/icf/lib/python3.10/site-packages/datalad_metalad/extract.py", line 859, in legacy_extract_file
    raise ValueError(
ValueError: unknown extractor class: type
```

`extract.py` checks which extractor class the current extractor is a subtype of here:

https://github.com/datalad/datalad-metalad/blob/8ca406d7050fd3328fafcc0c104b0791f4b5fb02/datalad_metalad/extract.py#L790:

and here:

https://github.com/datalad/datalad-metalad/blob/8ca406d7050fd3328fafcc0c104b0791f4b5fb02/datalad_metalad/extract.py#L832:

and neither of these evaluate to True, hence the value error. The reason is because `extract.py` imports from `datalad_metalad.extractors.base.BaseMetadataExtractor`, while the extension imports from `datalad_deprecated.metadata.extractors.base.BaseMetadataExtractor`. If I change the import in `extract.py` to the latter, everything works.

So we can make this update.

A follow-up question is whether the class `BaseMetadataExtractor` should be removed from `datalad_metalad.extractors.base`? @christian-monch any comments?

**Comment by jsheunis** [comment]
FTR: the plan is for the relevant extractor in this example to be upgraded to the latest generation of classes in metalad, although in the general case this shouldn't be expected to be the fix IMO.
