### ISSUE TITLE
Installation broken with PY3.12

### ISSUE THREAD

**Issue by mih** [datalad/datalad-metalad#397]
I installed v0.4.17 into a fresh environment (on windows), and I cannot import `datalad_metalad.extract` because it still uses the long deprecated `pkg_resources`. See https://github.com/datalad/datalad/pull/7439 for a related PR.

```
C:\Users\mih\code\datalad-container>python -c "import datalad_metalad.extract"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\mih\AppData\Local\Programs\Python\Python312\Lib\site-packages\datalad_metalad\extract.py", line 68, in <module>
    from .utils import (
  File "C:\Users\mih\AppData\Local\Programs\Python\Python312\Lib\site-packages\datalad_metalad\utils.py", line 2, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

```

**Comment by christian-monch** [comment]
Thanks for the issue. Fixed in PR #401
